### ISSUE TITLE
Failed to download JSONPress

### ISSUE THREAD

**Issue by StarlightDesign** [DanTheMan827/tikShop#2]
Tikshop used to work flawlessly, but I powered it up recently and it now fails to download new tickets. It gives the "failed to download JSONPress" error and kicks me back to the main menu.

Haven't seen anything on this online, any ideas as to what's happening? Thanks for the assistance.

**Comment by Hetor007** [comment]
https://github.com/DanTheMan827/tikShop/releases                
 tikshop 1.0.3

**Comment by StarlightDesign** [comment]
Cool, all up and running again. Cheers!
